# nome da pipeline
name: run Basic Testes

# em que momento será executada
on:
    pull_request: 
        branches: [master]

jobs:
    # o que vai ser feito nesse pipeline
    #só teremos um job: rodar os testes
    cypress-run:
        # maquina que será executada
        runs-on: Windows 10 Pro 

        # passo a passo para rodar os testes
        steps:
            # clone do projeto
            - name: Checkout/Clone do projeto
              uses: actions/checkout@v4

            # exemplo de execução no terminal
            - name: Instalar dependencias do projeto
              run: npm install

            # execução e configuração do projeto
            - name: Run testes
              uses: cypress-io/github-action@v6  
              with:
                record: true
              env:    
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

